# ------------------------------------------------------------------------------
# Style checkers / formatters
# ------------------------------------------------------------------------------

- id: style-java
  name: Check/fix Java style (google-java-format)
  types_or: [java]
  language: docker_image
  entry: tibi/pre-commit-hooks:20250419111018.e97352d0
  args: ["/hooks/style-java"]

- id: style-json
  name: Check/fix JSON style (prettier)
  types_or: [json]
  language: docker_image
  entry: tibi/pre-commit-hooks:20250419111018.e97352d0
  args: ["/hooks/style-json"]

- id: style-kotlin
  name: Check/fix Kotlin style (ktfmt)
  types_or: [kotlin]
  language: docker_image
  entry: tibi/pre-commit-hooks:20250419111018.e97352d0
  args: ["/hooks/style-kotlin"]

- id: style-markdown
  name: Check/fix Markdown style (prettier)
  types_or: [markdown]
  language: docker_image
  entry: tibi/pre-commit-hooks:20250419111018.e97352d0
  args: ["/hooks/style-markdown"]

- id: style-php
  name: Check/fix PHP style (prettier)
  types_or: [php]
  language: docker_image
  entry: tibi/pre-commit-hooks:20250419111018.e97352d0
  args: ["/hooks/style-php"]

- id: style-shell
  name: Check/fix shell style (shfmt)
  types_or: [shell]
  language: docker_image
  entry: tibi/pre-commit-hooks:20250419111018.e97352d0
  args: ["/hooks/style-shell"]

- id: style-xml
  name: Check/fix XML style (xmllint)
  types_or: [xml]
  language: docker_image
  entry: tibi/pre-commit-hooks:20250419111018.e97352d0
  args: ["/hooks/style-xml"]

- id: style-yaml
  name: Check/fix YAML style (prettier)
  types_or: [yaml]
  language: docker_image
  entry: tibi/pre-commit-hooks:20250419111018.e97352d0
  args: ["/hooks/style-yaml"]

# ------------------------------------------------------------------------------
# Linters
# ------------------------------------------------------------------------------

- id: lint-shell
  name: Check shell scripts for problems (shellcheck)
  types_or: [shell]
  language: docker_image
  entry: tibi/pre-commit-hooks:20250419111018.e97352d0
  args: ["/hooks/lint-shell"]

- id: lint-makefile-suspicious-continuations
  name: Check Makefiles for suspicious continuations
  types_or: [makefile]
  language: pygrep
  entry: '\\[ \t]+$'

- id: lint-makefile-suspicious-lines
  name: Check Makefiles for suspicious lines
  types_or: [makefile]
  language: pygrep
  entry: '^(\t+$| +\t)'

# ------------------------------------------------------------------------------
# Commit message preparation and linting
# ------------------------------------------------------------------------------

- id: commit-msg-check
  name: Check commit message (commitlint)
  stages: [commit-msg]
  language: docker_image
  entry: tibi/pre-commit-hooks:20250419111018.e97352d0
  args: ["/hooks/commit-msg-check"]

- id: commit-msg-restore
  name: Restore previously rejected commit message
  stages: [prepare-commit-msg]
  # This hook requires the `GIT_EDITOR` environment variable to be correctly
  # set.  As of pre-commit v4.2.0 this variable is not passed to the hook when
  # invoked through `docker_image`.  Therefore, this hook is defined with the
  # `script` language.
  language: script
  entry: ./hooks/commit-msg-restore
  # language: docker_image
  # entry: tibi/pre-commit-hooks:20250419111018.e97352d0
  # args: ["/hooks/commit-msg-restore"]
